# Generated by Django 5.1.6 on 2025-03-24 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_user_followers_alter_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='users_who_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
